name: Sync LeetCode Solutions

on:
  schedule:
    - cron: "0 0 * * *"  # Runs once a day
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Ensure repo write access
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to the latest version

      - name: Sync LeetCode solutions
        uses: yihong0618/leetcode-sync@main
        env:
          LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LEETCODE_LANGUAGE: "Python,C++,JavaScript,TypeScript"

      - name: Debug Information
        run: echo "LeetCode Sync Workflow Completed"

      - name: Handle Errors
        if: failure()
        run: echo "Error occurred during LeetCode sync"
