name: Sync LeetCode Solutions

on:
  schedule:
    - cron: "0 0 * * *"  # Runs once a day
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Sync LeetCode solutions
        uses: Yihong0618/leetcode-sync@v1.3
        env:
          LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LEETCODE_LANGUAGE: "Python,C++,JavaScript,TypeScript"
